version: "3.8"

services:
  api-generic:
    build: .
    container_name: api-generic
    volumes:
      - ../api-generic:/var/www
    ports:
      - "9001:9000"
    networks:
      - backend-network

  dev-server:
    build: .
    container_name: api-generic-dev
    command: php artisan serve --host=0.0.0.0 --port=8001
    volumes:
      - ../api-generic:/var/www
    ports:
      - "8001:8001"
    networks:
      - backend-network

networks:
  backend-network:
    external: true
