version: "3.8"

services:
  api-generic:
    build: .
    container_name: api-generic
    volumes:
      - .:/var/www
    networks:
      - backend-network
    expose:
      - "9000"

  nginx-generic:
    image: nginx:alpine
    container_name: nginx-generic
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-generic
    networks:
      - backend-network

networks:
  backend-network:
    external: true
